spring.application.name=emi-service

spring.datasource.url=jdbc:mysql://mysql:3306/loan_management_system
spring.datasource.username=loan_user
spring.datasource.password=loan_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server.port=8084

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=emi-service:${server.port}

logging.level.root=INFO
logging.level.com.lms=DEBUG
spring.cloud.config.enabled=false
